async function bubsort(){
    console.log('in bubble sort func');// just to print in the console... as a professional thing to do... 
    const elem=document.querySelectorAll(".bar");// select all the bars... by using queryselectorall which inturn returns a array of bars....
    for(let i=0;i<elem.length-1;i++)
    {
        console.log('outer loop');
        for(let j=0;j<elem.length-i-1;j++)// use improved bubble sorting coz normal one is not working...
        {
            console.log('inner loop');
            elem[j].style.background='blue';// these css properties all are in string format....
            elem[j+1].style.background='blue';
            if(parseInt(elem[j].style.height)>parseInt(elem[j+1].style.height)){// parseint is used to convert a string into numeric....
                console.log('entered into the if condition');
                await waitforme(delay);
                swap(elem[j],elem[j+1]);
            }
            elem[j].style.background='cyan';
            elem[j+1].style.background='cyan';
        }
        // after completion of inner loop the last element will be in its sorted position so make it green.... 
        elem[elem.length-1-i].style.background='green';// this is bcoz after every inner loop completion starting from the last position the element will be in their sorted position... example after completion of 1st iteration of outer loop the last pos is sorted and after 2nd iteration of outer loop the last-1 pos is sorted nd so on...
    }
    elem[0].style.background='green';
}
const bubbsortbtn=document.querySelector("#bubsort");// if the user clicks on bubble sort button.... then add a event listener for the following tasks..
bubbsortbtn.addEventListener('click',async function(){
    disableSortingBtn();//disables all the sorting buttons...
    disableSizeSlider();//disable the sizerangeslider....
    disablenewarraybtn();//disable the newarray button....
    await bubsort();// after disabling wait until the bubblesort function executes the program...
    enableSizeSlider();// after the execution is done enable all the buttons again....
    enableSortingBtn();
    enablenewarraybtn();
})
